# YML file that uploads the powershell module to the PowerShell Gallery

name: Publish Module to PowerShell Gallery

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Required Modules, Update Manifests, Publish updated Modules, and commit manifest changes
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
        run: |
          #Install Required Modules
          Install-module powershellget -force -Allowclobber
          Import-Module powershellget
          Install-Module -Name PartnerCenter -Force -AllowClobber
          Import-Module PartnerCenter

          #Import and Run Scripts
          $workingdirectory = (Get-Location).path
          . "$workingdirectory\.github\workflows\scripts\Generate-Manifest.ps1"
          . "$workingdirectory\.github\workflows\scripts\Publish-Modules.ps1"
          Publish-Modules

          #Publish new manifest files to the repository
          git config --global user.email "paul.boerdonk@icloud.com"
          git config --global user.name "Paul van Boerdonk"
          git add -A
          git commit -m "rel: Manifest Update"
          git push -u origin main
