name: Publish Module to PowerShell Gallery

on:
  push:
    branches:
      - main

jobs:
  publish-module-to-powershell-gallery:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up PowerShell
        shell: pwsh
        run: |
          Install-Module -Name PowerShellGet, PartnerCenter -Force -AllowClobber
          Import-Module PowerShellGet, PartnerCenter

      - name: Publish Module to PowerShell Gallery
        env:
          PS_GALLERY_KEY: ${{ secrets.PS_GALLERY_KEY }}
        shell: pwsh
        run: |
          $workingdirectory = (Get-Location).Path
          . "$workingdirectory\.github\workflows\scripts\Publish-Modules.ps1"
          Publish-Modules

      - name: Commit and push new files to GitHub
        shell: pwsh
        run: |
          git config --global user.email "paul.boerdonk@icloud.com"
          git config --global user.name "Paul van Boerdonk"
          git add -A
          git commit -m "Github Action: Publish Module to PowerShell Gallery"
          git push -u origin main
